import "./globals.css";
import "@mantine/carousel/styles.css";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import MantineTheme from "../../mantine.config";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/context/query";

export const metadata: Metadata = {
  title: "Cosmic Kids Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <div>
          <Toaster position="top-left" />
        </div>
        <MantineProvider theme={MantineTheme}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
